### ISSUE TITLE
two cecotec do not work at the same time

### ISSUE THREAD

**Issue by surri4** [congatudo/Congatudo#109]
I'm trying to configure two cecotec conga, but I can't, it only works if I configure one of them. Condo configured both, they communicate with my homeassitant, but the add-on detects them as one and the information it shows alternates between the two, sending them an order becomes impossible because you don't know which one you are sending it to. Has anyone been able to get two to work at the same time well? Thank you, Greetings.

**Comment by elraro** [comment]
Congatudo doesn't work with multiple devices. Use one instance of Congatudo per Conga, using multiple IPs/containers/vms/whatever.
