### ISSUE TITLE
Cannot edit Segments

### ISSUE THREAD

**Issue by EzeLamar** [congatudo/Congatudo#51]
## Describe the bug
Hi,
I cannot rename, split or merge Segments using the UI. When I try to do that I got the next error:
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/26080561/218289422-379d42ea-5bc6-413c-8019-4967808b8ff6.png">
And in the logs I got the next warning (rename action):
```
2023-02-12T02:18:31.334Z
Warn
Received "PUT "to "/api/v2/robot/capabilities/MapSegmentRenameCapability" with invalid payload [
  {
    keyword: 'type',
    dataPath: '.segment_id',
    schemaPath: '#/properties/segment_id/type',
    params: { type: 'string' },
    message: 'should be string'
  }
]
```

## To Reproduce
1. Create a new map by zero
2. Try to edit a Segment
3. See error

### Vacuum Model
Conga 3490

### Congatudo Version
0.2.5 - 2022-10-21 (latest version)

Thanks!

**Comment by elraro** [comment]
Please, this error is related with Congatudo addon.

We need to change the docker base image in the addon.

https://github.com/congatudo/congatudo-add-on/issues

Please open a issue

**Comment by EzeLamar** [comment]
Oh I see, sorry about that. I will open another issue in congatudo-add-on repository
