### ISSUE TITLE
WifiConfigurationCapabilityRouter: Error while handling route "/" 

### ISSUE THREAD

**Issue by germanyague** [congatudo/Congatudo#68]
[WARN] WifiConfigurationCapabilityRouter: Error while handling route "/" {
body: {},
message: "Cannot read properties of null (reading 'toString')"
}

## To Reproduce
Fresh install with a factory reseted Conga 3090. The /etc/wifi/wpa_suplicant.conf file was edited to:

ctrl_interface=/etc/wifi/sockets
update_config=1
network={
        ssid="WIFINAME"
        psk="PASSWORD"
}
-->

### Vacuum Model
Conga 3090

### Congatudo Version
2023.2.1 (same with 2023.3.0)

**Comment by elraro** [comment]
Hi @germanyague .

Please paste the output of `iw` command

**Comment by elraro** [comment]
Hi @germanyague ,

I think the problem is you are running Congatudo outside (container?) and the `embedded` variable from the config file is `true`. Please, change to `false` and try again.

**Comment by germanyague** [comment]
Sorry, I had no time left this week until now to test anything. 

**embedded:false** works! 
For future reference: 
`{
  "embedded": false,
  "robot": {
    "implementation": "CecotecCongaRobot",
    ...
}`
I'm running inside Docker on a Synology 920+, so I don't fully understand why I have to set embedded to false, but now I have no errors on my logs (I also had one about Congatudo not being able to set the correct time on the 3090).

Thank you.
