### ISSUE TITLE
Auto poweroff before battery runsout

### ISSUE THREAD

**Issue by MrMarble** [congatudo/Congatudo#74]
My cats like to sit on the robot and sometimes they unplug it, during the day I have an alert set up to warn me if it is unplugged for a while without cleaning, so I can plug it back in before the battery runs out, but this is not possible if it happens in the middle of the night.

Is there a way to turn off the robot remotely, either automatically from valetudo or manually with a home-assistant automation.

The main problem is that when the robot runs out of battery, the memory is erased, losing the map information:

![imagen](https://github.com/congatudo/Congatudo/assets/4268580/e3de5b60-06df-4e21-9885-2625faefc4c8)

### Vacuum Model
Conga 3490

### Congatudo Version
2023.04

**Comment by elraro** [comment]
@MrMarble You can check the Battery Level with the mqtt: https://congatudo.cloud/pages/integrations/mqtt.html#batterylevellevel

And send a ```poweroff``` vía SSH.
