### ISSUE TITLE
Doubt about the supported robots

### ISSUE THREAD

**Issue by ivanhercaz** [congatudo/Congatudo#98]
Hi!
First of all, thank you @elraro and the contributors for this awesome project to free our robots!

I have doubts about the supporting robots, because in [Supported Robots](https://congatudo.cloud/pages/general/supported-robots.html), that I understand it is an autogenerated documentation page, there isn't specific informations about models supported. However, in [Buying supported robots](https://congatudo.cloud/pages/general/buying-supported-robots.html) the suggestions are 3490 Elite and 4090.

Is there any possible way to confirm if a model is "possibly" supported? I have a Conga 4690 Ultra (model number 05553) and I really want to test with it ❤️ 

Thanks in advance for your time!

**Comment by ivanhercaz** [comment]
Ups, now I discovered the Telegram group. If you think this will fit better in the "General" channel I can ask the question there.

**Comment by elraro** [comment]
https://t.me/congatudo

The Model 4690 have SSL protocol, so now is not supported.
